name: CI - Pipeline smoke test + checks

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: "Install dependencies"
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas openpyxl pyogrio geopandas shapely pyproj
          pip install pytest flake8 statsmodels scipy

      - name: "Create WMATA-style fixture data (2019 single, 2023 single, 2024/2025 split)"
        run: |
          set -e
          mkdir -p data_raw data_geo results/tables data_clean

          # 2019 baseline (single file)
          printf '%s\n' \
            'Year of Date,Date,Day of Week,Holiday,Service Type,Station Name,Time Period,Avg Daily Tapped Entries,Entries,NonTapped Entries,SUM([NonTapped Entries])/COUNTD([Date]),Tap Entries' \
            '2019,2019-01-15,Tuesday,,Weekday,GALLERY PL-CHINATOWN,AM Peak,95,,5,,95' \
            '2019,2019-01-15,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Midday,75,,5,,75' \
            '2019,2019-01-15,Tuesday,,Weekday,GALLERY PL-CHINATOWN,PM Peak,115,,5,,115' \
            '2019,2019-01-15,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Evening,55,,5,,55' \
            '2019,2019-01-12,Saturday,,Saturday,UNION STATION,AM Peak,48,,2,,48' \
            '2019,2019-01-12,Saturday,,Saturday,UNION STATION,PM Peak,68,,2,,68' \
            > data_raw/ridership_2019.csv

          # 2023 (single file)
          printf '%s\n' \
            'Year of Date,Date,Day of Week,Holiday,Service Type,Station Name,Time Period,Avg Daily Tapped Entries,Entries,NonTapped Entries,SUM([NonTapped Entries])/COUNTD([Date]),Tap Entries' \
            '2023,2023-01-17,Tuesday,,Weekday,GALLERY PL-CHINATOWN,AM Peak,80,,2,,80' \
            '2023,2023-01-17,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Midday,72,,3,,72' \
            '2023,2023-01-17,Tuesday,,Weekday,GALLERY PL-CHINATOWN,PM Peak,100,,2,,100' \
            '2023,2023-01-17,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Evening,50,,1,,50' \
            '2023,2023-01-14,Saturday,,Saturday,UNION STATION,AM Peak,45,,1,,45' \
            '2023,2023-01-14,Saturday,,Saturday,UNION STATION,PM Peak,62,,1,,62' \
            > data_raw/ridership_2023.csv

          # 2024 (split: tapped)
          printf '%s\n' \
            'Year of Date,Date,Day of Week,Holiday,Service Type,Station Name,Time Period,Avg Daily Tapped Entries,Entries,NonTapped Entries,SUM([NonTapped Entries])/COUNTD([Date]),Tap Entries' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,AM Peak,85,,,' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Midday,78,,,' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,PM Peak,102,,,' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Evening,52,,,' \
            '2024,2024-01-13,Saturday,,Saturday,UNION STATION,AM Peak,47,,,' \
            '2024,2024-01-13,Saturday,,Saturday,UNION STATION,PM Peak,63,,,' \
            > data_raw/ridership_2024_tapped.csv

          # 2024 (split: non-tapped)
          printf '%s\n' \
            'Year of Date,Date,Day of Week,Holiday,Service Type,Station Name,Time Period,Avg Daily Tapped Entries,Entries,NonTapped Entries,SUM([NonTapped Entries])/COUNTD([Date]),Tap Entries' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,AM Peak,, ,2,,' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Midday,, ,2,,' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,PM Peak,, ,3,,' \
            '2024,2024-01-16,Tuesday,,Weekday,GALLERY PL-CHINATOWN,Evening,, ,1,,' \
            '2024,2024-01-13,Saturday,,Saturday,UNION STATION,AM Peak,, ,1,,' \
            '2024,2024-01-13,Saturday,,Saturday,UNION STATION,PM Peak,, ,1,,' \
            > data_raw/ridership_2024_nontapped.csv

          # 2025 (split: tapped)
          printf '%s\n' \
            'Year of Date,Date,Day of Week,Holiday,Service Type,Station Name,Time Period,Avg Daily Tapped Entries,Entries,NonTapped Entries,SUM([NonTapped Entries])/COUNTD([Date]),Tap Entries' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,AM Peak,88,,,' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,Midday,79,,,' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,PM Peak,105,,,' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,Evening,54,,,' \
            '2025,2025-01-18,Saturday,,Saturday,UNION STATION,AM Peak,49,,,' \
            '2025,2025-01-18,Saturday,,Saturday,UNION STATION,PM Peak,65,,,' \
            > data_raw/ridership_2025_tapped.csv

          # 2025 (split: non-tapped)
          printf '%s\n' \
            'Year of Date,Date,Day of Week,Holiday,Service Type,Station Name,Time Period,Avg Daily Tapped Entries,Entries,NonTapped Entries,SUM([NonTapped Entries])/COUNTD([Date]),Tap Entries' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,AM Peak,,,2,,' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,Midday,,,2,,' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,PM Peak,,,3,,' \
            '2025,2025-01-20,Monday,,Weekday,GALLERY PL-CHINATOWN,Evening,,,1,,' \
            '2025,2025-01-18,Saturday,,Saturday,UNION STATION,AM Peak,,,1,,' \
            '2025,2025-01-18,Saturday,,Saturday,UNION STATION,PM Peak,,,1,,' \
            > data_raw/ridership_2025_nontapped.csv

          # Minimal stations GeoJSON
          echo '{"type":"FeatureCollection","name":"metro_stations","crs":{"type":"name","properties":{"name":"EPSG:4326"}},"features":[{"type":"Feature","properties":{"NAME":"GALLERY PL-CHINATOWN"},"geometry":{"type":"Point","coordinates":[-77.0219,38.8983]}},{"type":"Feature","properties":{"NAME":"UNION STATION"},"geometry":{"type":"Point","coordinates":[-77.0075,38.8971]}}]}' > data_geo/metro_stations.geojson

      - name: "Convert fixture CSVs to UTF-16LE (simulate Tableau Download Data)"
        run: |
          set -e
          for f in data_raw/*.csv; do
            [ -f "$f" ] || continue
            iconv -f UTF-8 -t UTF-16LE "$f" > "${f}.utf16le"
            mv "${f}.utf16le" "$f"
            echo "Re-encoded $f to UTF-16LE"
          done

      - name: "Run 01_clean_data.py"
        env:
          PYTHONUTF8: "1"
        run: |
          set -e
          python analysis/01_clean_data.py

      - name: "Show cleaning outputs"
        run: |
          ls -lah data_clean || true
          ls -lah results/tables || true
          python -c "import json, pathlib; p=pathlib.Path('results/tables/clean_log.json'); print(p.read_text() if p.exists() else 'clean_log.json not found')"

      - name: "Verify schema of cleaned CSV"
        run: |
          set -e
          python -c "import pandas as pd, pathlib as pl; p=pl.Path('data_clean/station_monthly_recovery.csv'); assert p.exists(), 'clean CSV missing'; df=pd.read_csv(p, nrows=10000); cols=set(df.columns); required={'Station','Year','Month','Time_Period','Day_Type','Entries','Entries_2019','Denom_Flag'}; missing=required-cols; assert not missing, f'Missing baseline columns: {missing}'; ratio=('Recovery_Ratio_Final' if 'Recovery_Ratio_Final' in cols else ('Recovery_Ratio' if 'Recovery_Ratio' in cols else None)); assert ratio, 'Missing recovery ratio column'; assert len(df)>0, 'Empty CSV'; assert set(df['Time_Period'].dropna().unique())<= {'AM','MIDDAY','PM','EVENING'}, 'Unexpected Time_Period values'; print('Schema OK; using', ratio, '; rows=', len(df), '; stations≈', df['Station'].nunique())"

      - name: "Run 02_inference_tests.py"
        run: |
          set -e
          python analysis/02_inference_tests.py || true

      - name: "Verify inference JSON (tolerant)"
        run: |
          set -e
          python -c "import json, pathlib, math; p=pathlib.Path('results/tables/stats_summary.json'); assert p.exists(), 'stats_summary.json missing'; d=json.loads(p.read_text()); print('keys:', list(d.keys())); pv=d.get('weekend_vs_weekday',{}).get('p_value'); ok=(pv is None) or (isinstance(pv,(int,float)) and (0<=pv<=1) and not math.isnan(pv)); assert ok, f'Invalid p_value: {pv}'; print('OK')"

      - name: "Run 03_tableau_export.py"
        run: |
          set -e
          python analysis/03_tableau_export.py

      - name: "Verify Tableau export geometry"
        run: |
          set -e
          python -c "import pandas as pd, pathlib as pl; p=pl.Path('data_clean/tableau_recovery.csv'); assert p.exists(), 'tableau_recovery.csv missing'; df=pd.read_csv(p); assert {'Longitude','Latitude'}.issubset(df.columns), 'Missing geometry columns'; cov=float(df[['Longitude','Latitude']].notna().mean().mean()); print('Geometry coverage:', cov); assert cov>0.5, f'Low geometry coverage: {cov:.2f}'; print('Tableau export OK, rows=', len(df))"

      - name: "Run pytest"
        run: |
          set -e
          mkdir -p tests
          echo 'def test_placeholder(): assert True' > tests/test_placeholder.py
          pytest -q

      - name: "Lint (flake8, non-blocking)"
        run: |
          flake8 analysis --max-line-length=100 || true

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-outputs-${{ matrix.python-version }}
          path: |
            data_clean/**
            results/tables/**
          if-no-files-found: warn