name: CI - Pipeline smoke test + checks

on:
  push:
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas openpyxl pyogrio geopandas shapely pyproj
          pip install pytest flake8

      - name: Create fixture data
        run: |
          set -e
          mkdir -p data_raw data_geo results/tables data_clean

          printf '%s\n' \
            'Station,Year,Month,Time_Period,Day_Type,Entries' \
            'GALLERY PL-CHINATOWN,2019,1,AM,Weekday,100' \
            'GALLERY PL-CHINATOWN,2019,1,Midday,Weekday,80' \
            'GALLERY PL-CHINATOWN,2019,1,PM,Weekday,120' \
            'GALLERY PL-CHINATOWN,2019,1,Evening,Weekday,60' \
            'UNION STATION,2019,1,AM,Weekday,150' \
            'UNION STATION,2019,1,Midday,Weekday,90' \
            'UNION STATION,2019,1,PM,Weekday,130' \
            'UNION STATION,2019,1,Evening,Weekday,70' \
            'GALLERY PL-CHINATOWN,2019,1,AM,Weekend,40' \
            'UNION STATION,2019,1,AM,Weekend,50' \
            > data_raw/ridership_2019.csv

          printf '%s\n' \
            'Station,Year,Month,Time_Period,Day_Type,Entries' \
            'GALLERY PL-CHINATOWN,2023,1,AM,Weekday,82' \
            'GALLERY PL-CHINATOWN,2023,1,Midday,Weekday,75' \
            'UNION STATION,2023,1,AM,Weekday,140' \
            'UNION STATION,2023,1,PM,Weekday,110' \
            'GALLERY PL-CHINATOWN,2023,1,AM,Weekend,35' \
            'UNION STATION,2023,1,AM,Weekend,45' \
            > data_raw/ridership_2023_tapped.csv

          printf '%s\n' \
            'Station,Year,Month,Time_Period,Day_Type,Entries' \
            'GALLERY PL-CHINATOWN,2023,1,AM,Weekday,3' \
            'GALLERY PL-CHINATOWN,2023,1,Midday,Weekday,2' \
            'UNION STATION,2023,1,AM,Weekday,4' \
            'UNION STATION,2023,1,PM,Weekday,3' \
            'GALLERY PL-CHINATOWN,2023,1,AM,Weekend,1' \
            'UNION STATION,2023,1,AM,Weekend,2' \
            > data_raw/ridership_2023_nontapped.csv

          printf '%s\n' \
            '{' \
            '  "type": "FeatureCollection",' \
            '  "name": "metro_stations",' \
            '  "crs": { "type": "name", "properties": { "name": "EPSG:4326" } },' \
            '  "features": [' \
            '    {' \
            '      "type": "Feature",' \
            '      "properties": { "NAME": "GALLERY PL-CHINATOWN" },' \
            '      "geometry": { "type": "Point", "coordinates": [ -77.0219, 38.8983 ] }' \
            '    },' \
            '    {' \
            '      "type": "Feature",' \
            '      "properties": { "NAME"
